### ISSUE TITLE
I am wondering if there will release the result on the d4rl-v2 dataset in the future? And how to compute the normalized return? 

### ISSUE THREAD

**Issue by houmaolin** [takuseno/d3rlpy-benchmarks#2]

**Comment by takuseno** [comment]
Currently, I'm focusing on producing benchmark results for `-v0` with 10 random seeds each to make them available for journal submission. Once we get it accepted, we would work on `-v2` benchmarking.

**Comment by houmaolin** [comment]
> 

thanks for applying. 
![image](https://user-images.githubusercontent.com/22930365/174087194-76bda37f-a2fc-4795-bc46-bad0e66455a5.png)
In d4rl, I found the way for computing the normalized score.  but how could I get the expert score and random score used in the picture? Is there a certain number for every task, or I should run SAC and random policy in every task to get the certain score?

**Comment by takuseno** [comment]
Here it is.
https://github.com/rail-berkeley/d4rl/blob/master/d4rl/gym_mujoco/__init__.py#L23

**Comment by houmaolin** [comment]
> Here it is. https://github.com/rail-berkeley/d4rl/blob/master/d4rl/gym_mujoco/__init__.py#L23

Thanks a lot!

**Comment by houmaolin** [comment]
> 

Are those scores same between the v2 or v0?

**Comment by houmaolin** [comment]
> Here it is. https://github.com/rail-berkeley/d4rl/blob/master/d4rl/gym_mujoco/__init__.py#L23

Are those scores same between the v2 or v0?
