### ISSUE TITLE
Add learning d4rl mujoco dataset for *-random-v0/v2

### ISSUE THREAD

**Issue by im-Kitsch** [takuseno/d3rlpy-benchmarks#3]
Hi,

thanks for the excellent repo, I would like to ask could you add the test of *-expert-v2 data? 

I just tried to learning halfcheetah-expert-v0 dataset on AWAC, but unfortunately it learns nearly nothing, if you could add some tests on expert dataset, it would be quite helpful, thanks!

**Comment by takuseno** [comment]
Thank you for your request. I'm focusing on filling `-v0` datasets for journal submission. Once it's published, more datasets including `-expert-v0` will be added. 

Regarding AWAC training, I've observed that `AWAC` is not really robust for offline training. I'd recommend IQL unless you really need `AWAC`.
