### ISSUE TITLE
What's the level of Atari dataset used for benchmarking?

### ISSUE THREAD

**Issue by liyc-ai** [takuseno/d3rlpy-benchmarks#4]
Hi,

Thanks to your effort. It is a great work! I wonder what's the level of Atari dataset your used for benchmarking? expert, or mixed?

Thanks again.

**Comment by takuseno** [comment]
@BepfCp Hi. in this repository, I'm simply using the dataset provided by Google. Let me redirect you to this publication:
https://arxiv.org/abs/1907.04543

**Comment by liyc-ai** [comment]
Thanks for your reply.
